export const FETCH_MARKET_DATA = "FETCH_MARKET_DATA";
export const FETCH_ALL_COINS = "FETCH_ALL_COINS";
export const FETCH_COIN_HISTO = "FETCH_COIN_HISTO";

export const CREATE_PORTFOLIO = "CREATE_PORTFOLIO";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOGOUT_USER = "LOGOUT_USER";
